runtime: nodejs8
env: standard

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /api/.*
# secure: always
# redirect_http_response_code: 301
  script: auto
- url: /
  static_files: frontend/build/index.html
  upload: frontend/build/index.html
#- url: /.*
#  static_files: build/index.html
#  upload: build/index.html
