runtime: nodejs8
env: standard

instance_class: F4

handlers:
- url: /api/.*
  secure: always
  redirect_http_response_code: 301
  script: auto
- url: /
  static_files: frontend/build/index.html
  upload: frontend/build/index.html
#- url: /.*
#  static_files: build/index.html
#  upload: build/index.html
